from __future__ import annotations

from .services import state


class BaseConfig:
    BASE_DIR = state.BASE_DIR
    OUT_ROOT = state.OUT_ROOT
    JOB_ROOT = state.JOB_ROOT
    UPLOAD_ROOT = state.UPLOAD_ROOT
    DOC_WORKSPACE_ROOT = state.DOC_WORKSPACE_ROOT

    TRITON_URL = state.TRITON_URL
    PP_STRUCTURE_URL = state.PP_STRUCTURE_URL
    OPENAI_BASE_URL = state.OPENAI_BASE_URL
    OPENAI_API_KEY = state.OPENAI_API_KEY
    AZURE_BASE_URL = state.AZURE_BASE_URL
    AZURE_API_KEY_ENV = state.AZURE_API_KEY_ENV
    AZURE_BATCH_MODEL = state.AZURE_BATCH_MODEL
    AZURE_BATCH_POLL_SECONDS = state.AZURE_BATCH_POLL_SECONDS
    AZURE_BATCH_COMPLETION_WINDOW = state.AZURE_BATCH_COMPLETION_WINDOW
    AZURE_BATCH_SYSTEM_PROMPT = state.AZURE_BATCH_SYSTEM_PROMPT
    DOC_TRANSLATE_MODEL = state.DOC_TRANSLATE_MODEL
    PDF_REALTIME_TRANSLATE_MODEL = state.PDF_REALTIME_TRANSLATE_MODEL
    WORD_TRANSLATE_MODEL = state.WORD_TRANSLATE_MODEL
    WORD_QUALITY_MODEL = state.WORD_QUALITY_MODEL
    DOC_TRANSLATE_MAX_CHARS = state.DOC_TRANSLATE_MAX_CHARS
    DOC_TRANSLATE_USE_AZURE = state.DOC_TRANSLATE_USE_AZURE
    DOC_TRANSLATE_SYSTEM_PROMPT = state.DOC_TRANSLATE_SYSTEM_PROMPT
    DATABASE_URL = state.DATABASE_URL
    WORKER_POLL_SECONDS = state.WORKER_POLL_SECONDS
    WORKER_ID = state.WORKER_ID
    WORKER_OCR_MAX_RUNNING = state.WORKER_OCR_MAX_RUNNING
    WORKER_PDF_TRANSLATE_MAX_RUNNING = state.WORKER_PDF_TRANSLATE_MAX_RUNNING
    WORKER_DOC_MAX_RUNNING = state.WORKER_DOC_MAX_RUNNING
    WORKER_WORD_MAX_RUNNING = state.WORKER_WORD_MAX_RUNNING

    GLOSSARY_INSPECTION_PATH = state.GLOSSARY_INSPECTION_PATH
    GLOSSARY_PROCESS_PATH = state.GLOSSARY_PROCESS_PATH
    GLOBAL_GLOSSARY_PATH = state.GLOBAL_GLOSSARY_PATH
    SYSTEM_GLOSSARY_PATH = state.SYSTEM_GLOSSARY_PATH

    TRANSLATION_MEMORY_PATH = state.TRANSLATION_MEMORY_PATH
    TRANSLATION_MEMORY_TTL_DAYS = state.TRANSLATION_MEMORY_TTL_DAYS
    TRANSLATION_MEMORY_TTL_SECONDS = state.TRANSLATION_MEMORY_TTL_SECONDS

    DEFAULT_TEXT_COLOR = state.DEFAULT_TEXT_COLOR
    DEFAULT_FONT_SIZE_PX = state.DEFAULT_FONT_SIZE_PX

    TESTING = False


class TestingConfig(BaseConfig):
    TESTING = True


CONFIG_BY_NAME = {
    None: BaseConfig,
    "default": BaseConfig,
    "testing": TestingConfig,
}
