from __future__ import annotations

from .services import state


class BaseConfig:
    SECRET_KEY = state.SECRET_KEY
    BASE_DIR = state.BASE_DIR
    OUT_ROOT = state.OUT_ROOT
    JOB_ROOT = state.JOB_ROOT
    UPLOAD_ROOT = state.UPLOAD_ROOT
    DOC_WORKSPACE_ROOT = state.DOC_WORKSPACE_ROOT

    TRITON_URL = state.TRITON_URL
    PP_STRUCTURE_URL = state.PP_STRUCTURE_URL
    OPENAI_BASE_URL = state.OPENAI_BASE_URL
    OPENAI_API_KEY = state.OPENAI_API_KEY
    AZURE_BASE_URL = state.AZURE_BASE_URL
    AZURE_API_KEY_ENV = state.AZURE_API_KEY_ENV
    AZURE_BATCH_MODEL = state.AZURE_BATCH_MODEL
    AZURE_BATCH_POLL_SECONDS = state.AZURE_BATCH_POLL_SECONDS
    AZURE_BATCH_COMPLETION_WINDOW = state.AZURE_BATCH_COMPLETION_WINDOW
    AZURE_BATCH_SYSTEM_PROMPT = state.AZURE_BATCH_SYSTEM_PROMPT
    DOC_TRANSLATE_MODEL = state.DOC_TRANSLATE_MODEL
    PDF_REALTIME_TRANSLATE_MODEL = state.PDF_REALTIME_TRANSLATE_MODEL
    WORD_TRANSLATE_MODEL = state.WORD_TRANSLATE_MODEL
    WORD_QUALITY_MODEL = state.WORD_QUALITY_MODEL
    DOC_TRANSLATE_MAX_CHARS = state.DOC_TRANSLATE_MAX_CHARS
    DOC_TRANSLATE_USE_AZURE = state.DOC_TRANSLATE_USE_AZURE
    DOC_TRANSLATE_SYSTEM_PROMPT = state.DOC_TRANSLATE_SYSTEM_PROMPT
    DATABASE_URL = state.DATABASE_URL
    WORKER_POLL_SECONDS = state.WORKER_POLL_SECONDS
    WORKER_ID = state.WORKER_ID
    WORKER_OCR_MAX_RUNNING = state.WORKER_OCR_MAX_RUNNING
    WORKER_PDF_TRANSLATE_MAX_RUNNING = state.WORKER_PDF_TRANSLATE_MAX_RUNNING
    WORKER_DOC_MAX_RUNNING = state.WORKER_DOC_MAX_RUNNING
    WORKER_WORD_MAX_RUNNING = state.WORKER_WORD_MAX_RUNNING

    GLOSSARY_INSPECTION_PATH = state.GLOSSARY_INSPECTION_PATH
    GLOSSARY_PROCESS_PATH = state.GLOSSARY_PROCESS_PATH
    GLOBAL_GLOSSARY_PATH = state.GLOBAL_GLOSSARY_PATH
    SYSTEM_GLOSSARY_PATH = state.SYSTEM_GLOSSARY_PATH

    TRANSLATION_MEMORY_PATH = state.TRANSLATION_MEMORY_PATH
    TRANSLATION_MEMORY_TTL_DAYS = state.TRANSLATION_MEMORY_TTL_DAYS
    TRANSLATION_MEMORY_TTL_SECONDS = state.TRANSLATION_MEMORY_TTL_SECONDS

    DEFAULT_TEXT_COLOR = state.DEFAULT_TEXT_COLOR
    DEFAULT_FONT_SIZE_PX = state.DEFAULT_FONT_SIZE_PX
    AUTH_ENABLED = state.AUTH_ENABLED
    AUTH_STUB_ENABLED = state.AUTH_STUB_ENABLED
    AUTH_REQUIRE_LOCAL_USER = state.AUTH_REQUIRE_LOCAL_USER
    AUTHZ_MODE = state.AUTHZ_MODE
    OWNER_ACCESS_ENABLED = state.OWNER_ACCESS_ENABLED
    BOOTSTRAP_ADMIN = state.BOOTSTRAP_ADMIN
    SESSION_COOKIE_NAME = state.SESSION_COOKIE_NAME
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = "Lax"
    SESSION_COOKIE_SECURE = state.SESSION_COOKIE_SECURE
    LDAP_HOST = state.LDAP_HOST
    LDAP_PORT = state.LDAP_PORT
    LDAP_USE_SSL = state.LDAP_USE_SSL
    LDAP_BASE_DN = state.LDAP_BASE_DN
    LDAP_BIND_DN = state.LDAP_BIND_DN
    LDAP_BIND_PASSWORD = state.LDAP_BIND_PASSWORD
    LDAP_USER_LOGIN_ATTR = state.LDAP_USER_LOGIN_ATTR
    LDAP_USER_OBJECT_FILTER = state.LDAP_USER_OBJECT_FILTER
    LDAP_USER_DISPLAY_ATTR = state.LDAP_USER_DISPLAY_ATTR
    LDAP_USER_EMAIL_ATTR = state.LDAP_USER_EMAIL_ATTR
    LDAP_USER_SEARCH_SCOPE = state.LDAP_USER_SEARCH_SCOPE
    LDAP_GROUP_GATE_ENABLED = state.LDAP_GROUP_GATE_ENABLED
    ALLOWED_GROUP_DN = state.ALLOWED_GROUP_DN

    TESTING = False


class TestingConfig(BaseConfig):
    TESTING = True
    AUTH_ENABLED = False
    AUTH_REQUIRE_LOCAL_USER = False
    AUTHZ_MODE = "ad_all_users"
    OWNER_ACCESS_ENABLED = True


CONFIG_BY_NAME = {
    None: BaseConfig,
    "default": BaseConfig,
    "testing": TestingConfig,
}
